name = "email-generator-worker"
main = "src/server/worker.ts"
compatibility_date = "2025-10-10"
workers_dev = true

[[routes]]
pattern = "email-generator-worker.my-domain.com"
custom_domain = true

[version_metadata]
binding = "CF_VERSION_METADATA"

[observability]
enabled = true
head_sampling_rate = 1