export const t4passwordChange = {
  Set_New_Password: {
    en: "Set New Password",
    de: "Neues Passwort festlegen",
    ru: "Установить новый пароль",
    tj: "Пароли нави гузошед",
  },
  Hi_name: {
    en: "Hi [X],",
    de: "Hallo [X],",
    ru: "Привет, [X],",
    tj: "Салом [X],",
  },
  Hello: {
    en: "Hello,",
    de: "Hallo,",
    ru: "Здравствуйте,",
    tj: "Салом,",
  },
  You_requested_to_change_or_reset_your_password_on: {
    en: "You requested to change or reset your password on",
    de: "Sie haben angefordert, Ihr Passwort zu ändern oder zurückzusetzen auf",
    ru: "Вы запросили изменение или сброс пароля на",
    tj: "Шумо дархост кардед, ки пароли худро иваз ё аз нав созед дар",
  },
  Password_change_code_x: {
    en: "Password change code is [X]",
    de: "Passwortänderungscode ist [X]",
    ru: "Код смены пароля: [X]",
    tj: "Рамзи ивази парол: [X]",
  },
  Your_password_change_code_is: {
    en: "Your password change code is:",
    de: "Ihr Code für die Passwortänderung ist:",
    ru: "Ваш код для смены пароля:",
    tj: "Рамзи ивази пароли шумо аст:",
  },
  Copy_and_paste_this_password_change_code: {
    en: "Copy and paste this password change code:",
    de: "Kopieren und fügen Sie diesen Code für die Passwortänderung ein:",
    ru: "Скопируйте и вставьте этот код для смены пароля:",
    tj: "Ин рамзи ивази паролро нусхабардорӣ ва гузоред:",
  },
  Password_change_link: {
    en: "Change password with magic link",
    de: "Passwort über Link ändern",
    ru: "Изменить пароль по волшебной ссылке",
    tj: "Иваз кардани парол бо пайванди ҷодуӣ",
  },
  This_code_expires_in_x_minutes: {
    en: "This code expires in [X] minutes for security reasons.",
    de: "Dieser Code läuft aus Sicherheitsgründen in [X] Minuten ab.",
    ru: "Этот код истекает через [X] минут по соображениям безопасности.",
    tj: "Ин рамз ба сабаби бехатарӣ дар [X] дақиқа мегузарад.",
  },
  If_you_didnt_request_this_ignore: {
    en: "If you didn't request this, please ignore this email or contact support immediately.",
    de: "Wenn Sie dies nicht angefordert haben, ignorieren Sie diese E-Mail oder kontaktieren Sie umgehend den Support.",
    ru: "Если вы не запрашивали это, проигнорируйте это письмо или немедленно свяжитесь с поддержкой.",
    tj: "Агар шумо инро дархошта набошед, лутфан ин имейлро нодида гузаред ё бо дастгирӣ тамос кунед.",
  },
  If_you_didnt_request_this_change: {
    en: "If you didn't request this, please ignore this email or",
    de: "Wenn Sie dies nicht angefordert haben, ignorieren Sie diese E-Mail oder",
    ru: "Если вы не запрашивали это, проигнорируйте это письмо или",
    tj: "Агар шумо инро дархошта набошед, лутфан ин имейлро нодида гузаред ё",
  },
  Hello_you_requested_to_change_your_password_on_x: {
    en: "Hello,\n\nYou requested to change or reset your password on [X].",
    de: "Hallo,\n\nSie haben angefordert, Ihr Passwort auf [X] zu ändern oder zurückzusetzen.",
    ru: "Здравствуйте,\n\nВы запросили изменение или сброс пароля на [X].",
    tj: "Салом,\n\nШумо дархост кардед, ки пароли худро дар [X] иваз кунед ё аз нав созед.",
  },
  Thanks_the_x_team: {
    en: "Thanks,\nThe [X] Team",
    de: "Vielen Dank,\nDas [X]-Team",
    ru: "Спасибо,\nКоманда [X]",
    tj: "Ташаккур,\nГурӯҳи [X]",
  },
  Contact_support: {
    en: "contact support",
    de: "kontaktieren Sie den Support",
    ru: "связаться с поддержкой",
    tj: "бо дастгирӣ тамос кунед",
  },
} as const
